import React,{useState} from 'react'
import Head from 'next/head'
import Layout from '../../components/Layout'
import TopHeader from '../../components/TopHeader'
import Dashboard from '../../components/User/Dashboard'
import Orders from '../../components/User/Orders'
import OrderDetail from '../../components/User/OrderDetail'

const AllOrders = () => {
  const[returnProduct, setReturnProduct]= useState(false)
  return (
    <>
       <Head>
        <title>Orders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/image/favicon.ico" />
      </Head>
      <TopHeader />
    <Layout>
      <Dashboard>
        {!returnProduct ?(<div>
          <OrderDetail />
          <Orders setReturnProduct={setReturnProduct} />
        </div>):(
           <div className="px-4">
           <h2 className="font-semibold mb-2 mt-6 uppercase font-Orpheu font-medium tracking-wide text-xl">
           Return</h2>
       <div className="mt-4">
       <label htmlFor="email" className="block flex text-sm font-medium text-gray-700 mt-4">
       Reason for Return <div className="text-red-500">*</div>
     </label>
     <div className="mt-1">
       <input
         id="new"
         name="new"
         type="text"

         className="shadow-sm border-black border   px-4 py-2 w-full sm:text-lg  rounded-md"
       />
     </div>
     <label htmlFor="email" className="block flex text-sm font-medium text-gray-700 mt-4">
     Reason Details <div className="text-red-500">*</div>
     </label>
     <div className="mt-1">
       <input
         id="new"
         name="new"
         type="text"

         className="shadow-sm border-black border   px-4 py-2 w-full sm:text-lg  rounded-md"
       />
     </div>
     <label htmlFor="email" className="block flex text-sm font-medium text-gray-700 mt-4">
     Comments
     </label>
     <div className="mt-1">
       <input
         id="new"
         name="new"
         type="text"

         className="shadow-sm border-black border   px-4 py-2 w-full sm:text-lg  rounded-md"
       />
     </div>
     <h2 className="font-semibold mb-2 mt-6 uppercase font-Orpheu font-medium tracking-wide text-xl">
           PICK UP ADDRESS</h2>
       <label htmlFor="email" className="block flex text-sm font-medium text-gray-700 mt-4">
       Street Address <div className="text-red-500">*</div>
     </label>
       <div className="mt-1 ">
         <input
           id="street-address"
           name="street-address"
           type="text"
           autoComplete="street-address"
           className="shadow-sm border-black border mb-1  px-4 py-2 w-full sm:text-lg  rounded-md"
           />
           <input
             id="street-address"
             name="street-address"
             type="text"
             autoComplete="street-address"
             className="shadow-sm border-black border   px-4 py-2 w-full sm:text-lg  rounded-md"
           />
         </div>
         <div className=" grid md:grid-cols-2 md:gap-x-4">
         <div>
     <label htmlFor="email" className="block text-sm font-medium text-gray-700 flex mt-4">
     Country <div className="text-red-500">*</div>
     </label>
     <div className="mt-1 ">
         <select
           id="country"
           name="country"
           autoComplete="country-name"
           className="shadow-sm border-black border   px-3 py-2 w-full sm:text-lg  rounded-md"
         >
           <option>United States</option>
           <option>Canada</option>
           <option>Mexico</option>
         </select>
       </div>
       </div>
     <div>
     <label htmlFor="email" className="block text-sm font-medium text-gray-700 flex mt-4">
     State/Province <div className="text-red-500">*</div>
     </label>
     <div className="mt-1 ">
       <select
         id="address-level1"
         name="address-level1"
         autoComplete="address-level1"
         className="shadow-sm border-black border   px-3 py-2 w-full sm:text-lg  rounded-md"
       >
         <option>New York</option>
         <option>Lowa</option>
         <option>Georgia</option>
       </select>
       </div>
       </div>
       <div>
         <label htmlFor="email" className="block text-sm font-medium text-gray-700 flex mt-4">
     City <div className="text-red-500">*</div>
     </label>
     <div className="mt-1">
       <input
         id="address-level2"
         name="address-level2"
         type="text"
         autoComplete="address-level2"
         className="shadow-sm border-black border   px-4 py-2 w-full sm:text-lg  rounded-md"
       />
     </div>
     </div>
       <div>
     <label htmlFor="email" className="block text-sm font-medium text-gray-700 flex mt-4">
     Zip/Postal Code<div className="text-red-500">*</div>
     </label>
     <div className="mt-1">
       <input
         id="postal-code"
         name="postal-code"
         type="text"
         autoComplete="postal-code"
         className="shadow-sm border-black border   px-4 py-2 w-full sm:text-lg  rounded-md"
       />
     </div>
     </div>

         </div>
         </div>
         <div className="flex items-center my-4">
           <input
             id="filter-mobile-billing-address"
             name="isAddressSameAsShipping"
             type="checkbox"
             defaultChecked={false}
             className="h-4 w-4 accent-maroon rounded text-indigo-600 focus:ring-indigo-500"
           />
           <label
             htmlFor="filter-mobile-billing-address"
             className="ml-3 min-w-0 flex-1 text-gray-500"
           >
           Use same delivered Address
           </label>
         </div>
         <div>
         <h2 className="font-semibold mb-2 mt-6 uppercase font-Orpheu font-medium tracking-wide text-xl">
          bank details</h2>

         <div className=" grid md:grid-cols-2 md:gap-x-4 ">
         <div>
     <label htmlFor="email" className="block text-sm font-medium text-gray-700 flex mt-4">
     Account number<div className="text-red-500">*</div>
     </label>
     <div className="mt-1">
       <input
         id="new"
         name="new"
         type="text"

         className="shadow-sm border-black border   px-4 py-2 w-full sm:text-lg  rounded-md"
       />
     </div>
       </div>
     <div>
     <label htmlFor="email" className="block text-sm font-medium text-gray-700 flex mt-4">
     Confrim Account number<div className="text-red-500">*</div>
     </label>
     <div className="mt-1">
       <input
         id="new"
         name="new"
         type="text"

         className="shadow-sm border-black border   px-4 py-2 w-full sm:text-lg  rounded-md"
       />
     </div>
       </div>
       <div>
         <label htmlFor="email" className="block text-sm font-medium text-gray-700 flex mt-4">
   Account holder name<div className="text-red-500">*</div>
     </label>
     <div className="mt-1">
       <input
         id="new"
         name="new"
         type="text"

         className="shadow-sm border-black border   px-4 py-2 w-full sm:text-lg  rounded-md"
       />
     </div>
     </div>
       <div>
     <label htmlFor="email" className="block text-sm font-medium text-gray-700 flex mt-4">
     Bank name<div className="text-red-500">*</div>
     </label>
     <div className="mt-1">
       <input
         id="confirm"
         name="confirm"
         type="text"

         className="shadow-sm border-black border   px-4 py-2 w-full sm:text-lg  rounded-md"
       />
     </div>
     </div>
     <div>
     <label htmlFor="email" className="block text-sm font-medium text-gray-700 flex mt-4">
    IFSC Code<div className="text-red-500">*</div>
     </label>
     <div className="mt-1">
       <input
         id="confirm"
         name="confirm"
         type="text"

         className="shadow-sm border-black border   px-4 py-2 w-full sm:text-lg  rounded-md"
       />
     </div>
     </div>
     </div>
         </div>
         <p className="my-3 min-w-0 flex-1 text-gray-500">Refund will be transferred to your Original Payment Mode within 2 business days after pick up is completed.</p>
         <div className="flex px-2 mb-20">
             <button className="text-lg mr-4 flex items-center justify-center p-2 border border-transparent  font-medium rounded-md shadow-sm text-white bg-maroon hover:bg-maroon sm:px-8  mt-2.5" onClick={()=>setReturnProduct(false)}>
             Confrim Return
             </button>
             <button className="text-lg flex items-center justify-center p-2 border border-maroon shadow-md font-medium rounded-md shadow-sm text-maroon bg-transparent hover:bg-[#fdf1f2] sm:px-8  mt-2.5"  onClick={()=>setReturnProduct(false)}>
               Go Back
             </button>
           </div>
           </div>
        )}
      </Dashboard>
    </Layout>
    </>
  )
}

export default AllOrders
