import React from 'react'
import Head from 'next/head'
import Layout from '../../components/Layout'
import TopHeader from '../../components/TopHeader'
import Dashboard from '../../components/User/Dashboard'
import List from '../../components/WishPage/List'
import Wish from "../../components/User/Wish"

const wishlist = () => {
  return (
    <>
     <Head>
        <title>WishList</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/image/favicon.ico" />
      </Head>
      <TopHeader />
    <Layout>
      <Dashboard>
        <Wish />

      </Dashboard>
    </Layout>
    </>
  )
}

export default wishlist
