import { CheckCircleIcon } from '@heroicons/react/solid'
import {  RadioGroup} from '@headlessui/react'
import {  useState } from 'react'
import Link from 'next/link'
import Image from 'next/image'
import Billing from "../components/Checkout/Address/Billing"
import Shipping from "../components/Checkout/Address/Shipping"
import OrderSummary from "../components/Checkout/OrderSummary"
import Head from 'next/head'
import Layout from '../components/Layout'
import TopHeader from '../components/TopHeader'


const deliveryMethods = [
  {
    id: 1,
    title: 'Standard',
    turnaround: '4–10 business days',
    price: '$5.00',
  },
  { id: 2, title: 'Express', turnaround: '2–5 business days', price: '$16.00' },
]
const paymentMethods = [
  { id: 'credit-card', title: 'Credit card' },
  { id: 'paypal', title: 'PayPal' },
  { id: 'etransfer', title: 'eTransfer' },
]


function classNames(...classes) {
  return classes.filter(Boolean).join(' ')
}

export default function Example() {
  const [selectedDeliveryMethod, setSelectedDeliveryMethod] = useState(
    deliveryMethods[0],
  )
  return (
    <div className=" bg-[#fdf1f2]">

      <Head>
        <title>CheckOut</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/image/favicon.ico" />
      </Head>
      <TopHeader />
      <Layout>
        <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-14 ">
          <div className="max-w-2xl mx-auto lg:max-w-none">
            <h1 className="sr-only">Checkout</h1>

            <form className="flex flex-col-reverse relative lg:grid lg:grid-cols-2 lg:gap-x-12 xl:gap-x-16">
              <div>
              <div className="container mx-auto  py-10">
    <div className="relative rounded-md border border-gray-200">
    <div className="grid sm:grid-cols-3 grid-cols-1  text-center sm:mx-6 gap-x-2 mx-10 gap-y-4  my-6">
    <div className="w-full sm:h-16 h-20 bg-gray-200 aspect-w-1 aspect-h-1 rounded-md overflow-hidden group-hover:opacity-75  lg:aspect-none">
        <img
          src="/images/payment/shop.png"
          alt=""
          className="w-full h-full object-center object-cover lg:w-full lg:h-full"
        />
      </div>
    <div className="w-full sm:h-16 h-20 bg-gray-200 aspect-w-1 aspect-h-1 rounded-md overflow-hidden group-hover:opacity-75  lg:aspect-none">
      <img
        src="/images/payment/pay.png"
        alt=""
        className="w-full h-full object-center object-cover lg:w-full lg:h-full"
      />
    </div>
    <div className="w-full sm:h-16 h-20 bg-gray-200 aspect-w-1 aspect-h-1 rounded-md overflow-hidden group-hover:opacity-75  lg:aspect-none">
        <img
          src="/images/payment/paypal.png"
          alt=""
          className="w-full h-full object-center object-cover lg:w-full lg:h-full"
        />
      </div>

        </div>
      <h2 className="absolute flex top-0 left-1/2 transform -translate-x-1/2 -translate-y-1/2">
        <span className="bg-[#fdf1f2] px-2 text-base font-medium">Express Checkout</span>
      </h2>
    </div>
  </div>
  <div className="relative mb-6">
          <div className="absolute inset-0 flex items-center" aria-hidden="true">
            <div className="w-full border-t border-gray-200"></div>
          </div>
          <div className="relative flex justify-center">
            <span className="px-4 bg-[#fdf1f2] text-base font-medium text-gray-500">
              OR
            </span>
          </div>
        </div>
               <Shipping/>
               <Billing/>
                <div className="mt-10 border-t border-gray-200 pt-10">
                  <RadioGroup
                    value={selectedDeliveryMethod}
                    onChange={setSelectedDeliveryMethod}
                  >
                    <RadioGroup.Label className="text-left font-Orpheu text-2xl">
                      Delivery method
                    </RadioGroup.Label>

                    <div className="mt-4 grid grid-cols-1 gap-y-6 sm:grid-cols-2 sm:gap-x-4">
                      {deliveryMethods.map((deliveryMethod) => (
                        <RadioGroup.Option
                          key={deliveryMethod.id}
                          value={deliveryMethod}
                          className={({ checked, active }) =>
                            classNames(
                              checked
                                ? 'border-transparent'
                                : 'border-gray-300',
                              active ? 'ring-2 ring-maroon' : '',
                              'relative bg-white border rounded-lg shadow-sm p-4 flex cursor-pointer focus:outline-none',
                            )
                          }
                        >
                          {({ checked, active }) => (
                            <>
                              <span className="flex-1 flex">
                                <span className="flex flex-col">
                                  <RadioGroup.Label
                                    as="span"
                                    className="block text-sm font-medium text-gray-900"
                                  >
                                    {deliveryMethod.title}
                                  </RadioGroup.Label>
                                  <RadioGroup.Description
                                    as="span"
                                    className="mt-1 flex items-center text-sm text-gray-500"
                                  >
                                    {deliveryMethod.turnaround}
                                  </RadioGroup.Description>
                                  <RadioGroup.Description
                                    as="span"
                                    className="text-sm font-medium text-gray-900"
                                  >
                                    {deliveryMethod.price}
                                  </RadioGroup.Description>
                                </span>
                              </span>
                              {checked ? (
                                <CheckCircleIcon
                                  className="h-5 w-5 text-maroon"
                                  aria-hidden="true"
                                />
                              ) : null}
                              <span
                                className={classNames(
                                  active ? 'border' : 'border-2',
                                  checked
                                    ? 'border-maroon'
                                    : 'border-transparent',
                                  'absolute -inset-px rounded-lg pointer-events-none',
                                )}
                                aria-hidden="true"
                              />
                            </>
                          )}
                        </RadioGroup.Option>
                      ))}
                    </div>
                  </RadioGroup>
                </div>

                {/* Payment */}

              </div>

              {/* Order summary */}
              <div>
              <OrderSummary/>
              </div>

            </form>
          </div>
        </main>
      </Layout>
    </div>
  )
}
