import Faq from "../components/home/Faq"
import Head from 'next/head'
import Layout from '../components/Layout'
import React from 'react'
import TopHeader from "../components/TopHeader"

const Faqs = () => {
  return <>
    <Head>
      <title>FAQs</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <TopHeader />
    <Layout>
      <Faq />
    </Layout>
  </>
}

export default Faqs
