import React from 'react'
import Layout from '../components/Layout'
import Head from 'next/head'
import TopHeader from '../components/TopHeader'
import Account from '../components/User/Account'
import Dashboard from '../components/User/Dashboard'

const user = () => {
  return (
    <>
    <Head>
        <title>Account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/image/favicon.ico" />
      </Head>
      <TopHeader />
    <Layout>
      <Dashboard>
        <Account />
      </Dashboard>
    </Layout>
    </>
  )
}

export default user
